name       : haskell-cairo
version    : 0.13.5.0
release    : 4
source     :
    - https://hackage.haskell.org/package/cairo-0.13.5.0/cairo-0.13.5.0.tar.gz : 420acd81e0b5578ad188bcdd38463135293c233221abb741cc4004d4c8a6bef3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Cairo is a library to render high quality vector graphics. There exist
    various backends that allows rendering to Gtk windows, PDF, PS, PNG and SVG documents,
    amongst others.
description: |
    Cairo is a library to render high quality vector graphics. There exist various backends that allows rendering to Gtk windows, PDF, PS, PNG and SVG documents, amongst others.
builddeps  :
    - pkgconfig(cairo)
    - ghc-devel
    - gtk2hs-buildtools-devel
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-hashtables-devel
    - haskell-mtl
    - haskell-primitive-devel
    - haskell-random-devel
    - haskell-text-devel
    - haskell-utf8-string
    - haskell-vector-devel
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
